services:
  lamb-re-widget:
    build: .
    container_name: lambre-widget-app
    networks:
      - proxy
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lamb-re-widget.rule=Host(`local.thelambrealestate.com`)"
      - "traefik.http.services.lamb-re-widget.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
